//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiForQuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EXAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_EXAM()
        {
            this.TBL_QUESTION = new HashSet<TBL_QUESTION>();
        }
    
        public long exam_id { get; set; }
        public string exam_Name { get; set; }
        public Nullable<long> exam_CreatedBy { get; set; }
        public string exam_AppearCode { get; set; }
        public Nullable<bool> exam_Status { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_QUESTION> TBL_QUESTION { get; set; }
    }
}
